### ISSUE TITLE
SVG output is empty

### ISSUE THREAD

**Issue by haucky** [Tw1ddle/geometrize-lib-example#3]
Hey Sam,

first of all congrats on your awesome project! I used your tool on various occasions - I even designed the gift card for my sisters marriage by merging together vectorized images! 

### My issue
When running packaged binary for Linux (`geometrize_lib_example_248_linux_clang++-3`) the png output works just fine. But for the SVG output is always empty - only with the root element. Have I missed some dependency or can you hint me on how to debug it? The running binary doesn't output the `Failed to write SVG file to:` defined in the `main.cpp`.
```xml
<?xml version="1.0" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.2" baseProfile="tiny" width="512" height="384" viewBox="0 0 512 384">
```

**Comment by Tw1ddle** [comment]
Happy to hear you found a great use for it :smile:

Funny bug, there were thousands of automatically built Linux binaries in the S3 bucket, so many that the listing didn't fetch them up to the most recent - so the one you had was an old one.

If you download one of the latest one, hopefully it'll be up to date and work now!

https://s3.amazonaws.com/geometrize-lib-example-bucket/index.html

**Comment by haucky** [comment]
ok! Perfect - that resolved the issue! Thank you very much! :-)
